### ISSUE TITLE
missing dependencies in package.json?

### ISSUE THREAD

**Issue by paulovieira** [anseki/plain-overlay#5]
Great little library, thanks for sharing!

But i've had a few problems to use it with webpack. The problem is there are several files/modules available after "npm install", and webpack seems to give preference to the "module" field over "main" (in package.json).

So webpack will use "plain-overlay.esm.js", which has 4 small dependencies ("cssprefix", "anim-event", "m-class-list", "timed-transition"). The build fails because these dependencies are not listed anywhere in package.json.

These modules should be in peerDependencies maybe?

Thanks.

**Comment by anseki** [comment]
Hi @paulovieira, thank you for the comment.

The `peerDependencies` is used for a plugin.
https://docs.npmjs.com/files/package.json#peerdependencies
You can install `devDependencies` packages by using `npm install --dev`.

**Comment by paulovieira** [comment]
Ah ok, those dependencies are in "devDependencies", I missed that.

But the problem remains: if I just want to use this module with webpack, I would expect to be able to do simpleste thing, that is:
```bash
npm install plain-overlay
```
and then in my application code:
```js
import PlainOverlay from 'plain-overlay'
```
or
```js
let PlainOverlay = require('plain-overlay')
```
But unfortunatelly this is not possible at the moment.

Maybe those 4 dependencies could be moved to the "dependencies" field?

Or maybe bundle those dependencies in the output?

Thanks.

**Comment by anseki** [comment]
Those packages should never be moved to the `dependencies` field because those packages are not required for running PlainOverlay. Otherwise, superfluous packages are always installed.

Those packages are used for building (development) the PlainOverlay production version.
Packages that are required for development should be added to the `devDependencies`, not `dependencies`.
See document: https://docs.npmjs.com/files/package.json#devdependencies

You are trying to do: `import`, bundling by Webpack, etc., it means development.

Also, as I said, you can install `devDependencies` packages easily by `npm install` or `--dev`.

This also might help you: https://github.com/webpack/webpack/issues/520

**Comment by anseki** [comment]
No reply came, and I close this issue.

**Comment by nguyenngoc2505** [comment]
Hi @anseki  I've problem when trying import PlainOverlay. Could you help me to resolve this. I've using yarn, npm install but it still got this error.  Thanks!

```
ERROR in ./node_modules/plain-overlay/plain-overlay.esm.js
Module not found: Error: Can't resolve 'anim-event' in '/Users/User/myapp/node_modules/plain-overlay'
 @ ./node_modules/plain-overlay/plain-overlay.esm.js 35:0-35 1162:44-53
ERROR in ./node_modules/plain-overlay/plain-overlay.esm.js
Module not found: Error: Can't resolve 'cssprefix' in '/Users/User/myapp/node_modules/plain-overlay'
 @ ./node_modules/plain-overlay/plain-overlay.esm.js 34:0-34 574:15-24 618:19-28 619:20-29 930:27-36
ERROR in ./node_modules/plain-overlay/plain-overlay.esm.js
Module not found: Error: Can't resolve 'm-class-list' in '/Users/User/myapp/node_modules/plain-overlay'
 @ ./node_modules/plain-overlay/plain-overlay.esm.js 36:0-38 55:0-10 601:83-93 625:94-104 661:2-12 785:30-40 1096:30-40 1106:34-44 1111:34-44
ERROR in ./node_modules/plain-overlay/plain-overlay.esm.js
Module not found: Error: Can't resolve 'timed-transition' in '/Users/User/myapp/node_modules/plain-overlay'
 @ ./node_modules/plain-overlay/plain-overlay.esm.js 37:0-47 1104:27-42
```

**Comment by anseki** [comment]
Hi @nguyenngoc2505, thank you for the comment.
If you want to use a NPM package in development mode, you have to install the package and `devDependencies` packages.
For example:
```
npm i plain-overlay
cd node_modules/plain-overlay
npm i
```

**Comment by nguyenngoc2505** [comment]
@anseki I've resolved my problem. Thanks for your support!

**Comment by anseki** [comment]
:smile:

**Comment by nguyenngoc2505** [comment]
Hi @anseki , I'am sorry for that i have an another question. I've resolved this problem on development mode but it still got problem when I'm deploying on prd server (I'm using heroku). This error effect on cssprefix 

```
 ModuleNotFoundError: Module not found: Error: Can't resolve 'cssprefix' in '/tmp/build_560a42d4/node_modules/plain-overlay'
           at /tmp/build_560a42d4/node_modules/webpack/lib/Compilation.js:925:10
           at /tmp/build_560a42d4/node_modules/webpack/lib/NormalModuleFactory.js:401:22
           at /tmp/build_560a42d4/node_modules/webpack/lib/NormalModuleFactory.js:130:21
           at /tmp/build_560a42d4/node_modules/webpack/lib/NormalModuleFactory.js:224:22
           at /tmp/build_560a42d4/node_modules/neo-async/async.js:2830:7
           at /tmp/build_560a42d4/node_modules/neo-async/async.js:6877:13
           at /tmp/build_560a42d4/node_modules/webpack/lib/NormalModuleFactory.js:214:25
           at /tmp/build_560a42d4/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:213:14
           at /tmp/build_560a42d4/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:285:5
           at eval (eval at create (/tmp/build_560a42d4/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:13:1)
           at /tmp/build_560a42d4/node_modules/webpack/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:44:7
           at /tmp/build_560a42d4/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:285:5
           at eval (eval at create (/tmp/build_560a42d4/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:13:1)
           at /tmp/build_560a42d4/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:285:5
           at eval (eval at create (/tmp/build_560a42d4/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:25:1)
           at /tmp/build_560a42d4/node_modules/webpack/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:67:43
           at /tmp/build_560a42d4/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:285:5
           at eval (eval at create (/tmp/build_560a42d4/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:26:1)
           at /tmp/build_560a42d4/node_modules/webpack/node_modules/enhanced-resolve/lib/ModuleKindPlugin.js:30:40
           at /tmp/build_560a42d4/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:285:5
           at eval (eval at create (/tmp/build_560a42d4/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:13:1)
           at /tmp/build_560a42d4/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:285:5
           at eval (eval at create (/tmp/build_560a42d4/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:14:1)
           at /tmp/build_560a42d4/node_modules/webpack/node_modules/enhanced-resolve/lib/forEachBail.js:30:14
           at /tmp/build_560a42d4/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:285:5
           at eval (eval at create (/tmp/build_560a42d4/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:13:1)
           at /tmp/build_560a42d4/node_modules/webpack/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:44:7
           at /tmp/build_560a42d4/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:285:5
           at eval (eval at create (/tmp/build_560a42d4/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:13:1)
           at /tmp/build_560a42d4/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:285:5
           at eval (eval at create (/tmp/build_560a42d4/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:25:1)
           at /tmp/build_560a42d4/node_modules/webpack/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:67:43
           at /tmp/build_560a42d4/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:285:5
           at eval (eval at create (/tmp/build_560a42d4/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:14:1)
           at /tmp/build_560a42d4/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:285:5
           at eval (eval at create (/tmp/build_560a42d4/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:25:1)
       resolve 'cssprefix' in '/tmp/build_560a42d4/node_modules/plain-overlay'
```

**Comment by anseki** [comment]
That error means that the cssprefix can not be found.
`devDependencies` packages were not installed maybe.
